---
title: "Dial-Jackson-homework4"
author: "Jackson Dial"
date: '2023-01-31'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


# Q1

## A

```{r}
x <- -15:15
y <- (exp(x) / (exp(x) + 1)^2)
dat <- cbind.data.frame(x,y)
ggplot(dat, aes(x = x, y = y))+
  geom_line()+
  theme(panel.grid.minor = element_blank())
```


## B

```{r}

```


# Q2

## Task 4

```{r}

#set seed for reproducibility
set.seed(123)

# spurters
x = c(18, 40, 15, 17, 20, 44, 38)

# control group
y = c(-4, 0, -19, 24, 19, 10, 5, 10,
      29, 13, -9, -8, 20, -1, 12, 21,
      -7, 14, 13, 20, 11, 16, 15, 27,
      23, 36, -33, 34, 13, 11, -19, 21,
      6, 25, 30,22, -28, 15, 26, -1, -2,
      43, 23, 22, 25, 16, 10, 29)

# store data in data frame 
iqData = data.frame(Treatment = c(rep("Spurters", length(x)), 
                                  rep("Controls", length(y))),
                                  Gain = c(x, y))
```


```{r}
prior = data.frame(m = 0, c = 1, a = 0.5, b = 50)
findParam = function(prior, data){
  postParam = NULL
  c = prior$c
  m = prior$m
  a = prior$a
  b = prior$b
  n = length(data)
  postParam = data.frame(m = (c*m + n*mean(data))/(c + n), 
                c = c + n, 
                a = a + n/2, 
                b =  b + 0.5*(sum((data - mean(data))^2)) + 
                  (n*c *(mean(data)- m)^2)/(2*(c+n)))
  return(postParam)
}
# Find parameters for each of the distributions we are wanting to pull from
postS = findParam(prior, x)
postC = findParam(prior, y)

# library(lestat)
# postDistS <- normalgamma(postS[1], postS[2], postS[3], postS[4])
# 
# sample(postDistS, size = 10)
# 
# plot(normalgamma(3,4,5,6))
```

```{r}
set.seed(456)
rnormgamma <- function(n, mu, lambda, alpha, beta) {
  if (length(n) > 1) 
    n <- length(n)
  tau <- rgamma(n, alpha, beta)
  x <- rnorm(n, mu, sqrt(1/(lambda*tau)))
  data.frame(tau = tau, x = x)
}



postSsamps <- rnormgamma(1000000,postS[,1], postS[,2], postS[,3], postS[,4])
postCsamps <- rnormgamma(1000000,postC[,1], postC[,2], postC[,3], postC[,4])
names(postSsamps) <- c("S_tau", "S_x")
names(postCsamps) <- c("C_tau", "C_x")

all_x <- cbind(postSsamps, postCsamps)

final <- all_x %>% 
  mutate(s_greater_c = case_when(
    S_x > C_x ~ 1,
    TRUE ~ 0
  ))

posterior_prob <- mean(final$s_greater_c)
#The posterior probability is 0.970645
```


This means the probability of the mean QI for spurters has a 97% probability of being higher than the mean QI score for the control group.

## Task 5

```{r}
#Priors are also Normal-Gamma
library(tictoc)
set.seed(789)
prior_df_loop <- data.frame()
tic()
for(i in 1:1000){
  prior_samps <- rnormgamma(1000, 0, 1, .5, 50)[,2]
  prior_mean <- mean(prior_samps)
  prior_sd <- sd(prior_samps)
  prior_row <- cbind(prior_mean, prior_sd)
  prior_df_loop <- rbind(prior_df_loop, prior_row)
}
toc()
ggplot(prior_df_loop,aes(x = prior_mean, y = prior_sd))+
  geom_point()+
  xlim(-50,50)+
  ylim(0,400)
```


It looks like the mean is about 0 and the standard deviation is likely between 20 and 100