---
title: "Dial-Jackson-homework7"
author: "Jackson Dial"
date: '2023-04-01'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in data

```{r}
setwd("C:/Users/jacks/OneDrive/Desktop/DUKE_SPRING2023/602/STA602/HW7")
orange <- read.table("orangecrab.dat.txt")
blue <- read.table("bluecrab.dat.txt")
```


# Part A

```{r}
n_or <- nrow(orange)
n_bl <- nrow(blue)

ybar_or <- c(mean(orange$V1), mean(orange$V2))
ybar_bl <- c(mean(blue$V1), mean(blue$V2))

sigma_or <- cov(orange)
sigma_bl <- cov(blue)

mu0_or <- ybar_or
L0_or <- sigma_or
nu0_or <- 4
S0_or <- L0_or

mu0_bl <- ybar_bl
L0_bl <- sigma_bl
nu0_bl <- 4
S0_bl <- L0_bl
```


```{r}
library(mvtnorm)
library(MCMCpack)
```


## Gibbs Sampler

```{r}
# orange
THETA_or <- SIGMA_or <- NULL
set.seed(1392)
for (s in 1:10000) {
  ## update theta
  Ln_or <- solve(solve(L0_or) + n_or*solve(sigma_or))
  mun_or <- Ln_or %*% (solve(L0_or) %*% mu0_or + 
                   n_or*solve(sigma_or) %*% ybar_or)
  theta_or <- rmvnorm(1, mun_or, Ln_or)
  
  ## update Sigma
  Sn_or <- S0_or + (t(orange) - c(theta_or)) %*% t(t(orange)-c(theta_or))
  
  Sigma_or <- solve(rwish(nu0_or + n_or, solve(Sn_or)))
  ## save results
  THETA_or <- rbind(THETA_or, theta_or)
  SIGMA_or <- rbind(SIGMA_or, c(Sigma_or))
}

n.iter<-10000
plot(1:n.iter, THETA_or[,1], pch = 16, cex = .35,
     xlab = "Iteration", ylab = expression(theta),
     main = expression(paste("Traceplot of ", theta)))

plot(1:n.iter, THETA_or[,2], pch = 16, cex = .35,
     xlab = "Iteration", ylab = expression(theta),
     main = expression(paste("Traceplot of ", theta, 2)))

run.avg_or <- apply(THETA_or, 2, cumsum)/(1:n.iter)
plot(1:n.iter, run.avg_or[,1], type = "l",
     xlab = "Iteration", ylab = expression(theta),
     main = expression(paste("Running Average Plot of ", theta)))

plot(1:n.iter, run.avg_or[,2], type = "l",
     xlab = "Iteration", ylab = expression(theta),
     main = expression(paste("Running Average Plot of ", theta, 2)))

plot(density(THETA_or[,1]), xlab = expression(theta), 
     main = expression(paste("Density of ", theta)))
abline(v = mean(THETA_or[,1]), col = "red")

plot(density(THETA_or[,2]), xlab = expression(theta), 
     main = expression(paste("Density of ", theta, 2)))
abline(v = mean(THETA_or[,2]), col = "red")

mean(THETA_or[,2] > THETA_or[,1])

```


```{r}
#blue
THETA_bl <- SIGMA_bl <- NULL
set.seed(1393)
for (s in 1:10000) {
  ## update theta
  Ln_bl <- solve(solve(L0_bl) + n_bl*solve(sigma_bl))
  mun_bl <- Ln_bl %*% (solve(L0_bl) %*% mu0_bl + 
                   n_bl*solve(sigma_bl) %*% ybar_bl)
  theta_bl <- rmvnorm(1, mun_bl, Ln_bl)
  
  ## update Sigma
  Sn_bl <- S0_bl + (t(blue) - c(theta_bl)) %*% t(t(blue)-c(theta_bl))
  
  Sigma_bl <- solve(rwish(nu0_bl + n_bl, solve(Sn_bl)))
  ## save results
  THETA_bl <- rbind(THETA_bl, theta_bl)
  SIGMA_bl <- rbind(SIGMA_bl, c(Sigma_bl))
}

n.iter <- 10000
plot(1:n.iter, THETA_bl[,1], pch = 16, cex = .35,
     xlab = "Iteration", ylab = expression(theta),
     main = expression(paste("Traceplot of ", theta)))

plot(1:n.iter, THETA_bl[,2], pch = 16, cex = .35,
     xlab = "Iteration", ylab = expression(theta),
     main = expression(paste("Traceplot of ", theta, 2)))

run.avg_bl <- apply(THETA_bl, 2, cumsum)/(1:n.iter)
plot(1:n.iter, run.avg_bl[,1], type = "l",
     xlab = "Iteration", ylab = expression(theta),
     main = expression(paste("Running Average Plot of ", theta)))

plot(1:n.iter, run.avg_bl[,2], type = "l",
     xlab = "Iteration", ylab = expression(theta),
     main = expression(paste("Running Average Plot of ", theta, 2)))

plot(density(THETA_bl[,1]), xlab = expression(theta), 
     main = expression(paste("Density of ", theta)))
abline(v = mean(THETA_bl[,1]), col = "red")

plot(density(THETA_bl[,2]), xlab = expression(theta), 
     main = expression(paste("Density of ", theta, 2)))
abline(v = mean(THETA_bl[,2]), col = "red")

mean(THETA_bl[,2] > THETA_bl[,1])

```

